### ISSUE TITLE
modgui-vpn traduzione

### ISSUE THREAD

**Issue by lorenzobucci** [FrancYescO/sharing_tg789#2]
Ho creato un file .po di traduzione in italiano. Se vuoi aggiungerlo, lo allego qui.
[webui-l2tp-ipsec-server.zip](https://github.com/FrancYescO/sharing_tg789/files/4023772/webui-l2tp-ipsec-server.zip)

**Comment by FrancYescO** [comment]
Se vuoi crea stesso una pull request che la accetto, altrimenti appena posso cerco di includerlo
